# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [2]:
#Let's start by importing the library
import torch

C:\miniconda3\envs\pytorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [3]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
t_2 = torch.Tensor(16,32,128,128)
# .size() allows to get the size of the tensor
print(t.size(), t_2.size())

torch.Size([2, 2, 4]) torch.Size([16, 32, 128, 128])


In [4]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)
t_zeros = torch.zeros(2,2,4)

In [5]:
# Print the tensors
print(t, t_r, t_ones, t_zeros)

tensor([[[9.0000e-39, 1.0010e-38, 9.9184e-39, 9.6429e-39],
         [1.0469e-38, 9.0919e-39, 1.0561e-38, 9.6429e-39]],

        [[9.4592e-39, 1.0286e-38, 1.0194e-38, 9.2755e-39],
         [1.0561e-38, 1.0286e-38, 1.6956e-43, 0.0000e+00]]]) tensor([[[ 0.5769,  2.4393, -2.1778, -0.2100],
         [-1.6139,  0.2121,  1.2238,  1.0891]],

        [[-2.1537,  0.1040,  1.5609,  1.6047],
         [-0.2675,  0.2248, -0.9131, -1.3581]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
# To resize a tensor do
t.resize_(4,4)
print(t.size())
t.resize_(16,16)
print(t.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([4, 4])
torch.Size([16, 16])


In [9]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([16, 16]) torch.Size([2, 2])


In [12]:
# Fill a tensor with a specific number
t_ones.fill_(3)
t_ones.fill_(64)
print(t_ones)

tensor([[[64., 64., 64., 64.],
         [64., 64., 64., 64.]],

        [[64., 64., 64., 64.],
         [64., 64., 64., 64.]]])


In [14]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)
print(v.size())

tensor([7., 8., 9.])
torch.Size([3])


Working with tensors is exactly like working with vectors and matrices!

In [18]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
print(w2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])
tensor([9., 4., 1.])


In [19]:
q = torch.randn(2,4,2)
p = torch.randn(2,3,2)

print(q + p)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [20]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [21]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [22]:
# like with vectors you can
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[-2.7169e-03,  1.8798e+00,  3.4732e+00,  3.1376e+00],
        [ 5.0201e+00,  6.9153e+00,  8.2856e+00,  7.0394e+00]])
tensor([[-1.0027, -0.2403,  1.4195, -3.4496],
        [ 0.1003,  5.4919,  8.9989, -7.6851]])


In [23]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


In [27]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [31]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(device)
print(m_d.device)

m.cpu()
m.cuda()

cuda:0
cuda:0


tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], device='cuda:0')

Moving tensors to Numpy

In [30]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [3]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [4]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)

# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())

# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([3, 64, 1, 64])
torch.Size([3, 64, 64])


In [ ]:
# Ex1: Split a 3 dimentional tensors of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them together to get the original size back

In [ ]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them together to form a single matrix
# of dimension 4x64x32

In [ ]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256