# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [1]:
#Let's start by importing the library
import torch

In [2]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
# .size() allows to get the size of the tensor
print(t.size())

torch.Size([2, 2, 4])


In [3]:
# Generate a random tensor  filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)

In [4]:
# Print both tensors
print(t, t_r, t_ones)

tensor([[[1.8469e+25, 8.7126e-04, 2.6451e+20, 4.4264e+30],
         [3.4059e-15, 7.3988e+31, 4.4849e+21, 2.7370e+20]],

        [[6.4640e-04, 7.9290e+29, 7.5546e+31, 1.6932e+22],
         [6.9722e+22, 1.7973e+19, 2.9967e+32, 1.7743e+28]]]) tensor([[[ 0.6660,  0.4533, -0.6711, -1.4615],
         [ 0.0671, -0.2241, -0.0953,  0.7024]],

        [[ 1.4280,  0.5156, -2.1508,  0.1397],
         [ 1.1536,  1.1900, -1.1291, -0.5654]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [5]:
# To resize a tensor do
t.resize_(4,4)
t.size()
# be CAREFULL with in-place operation like this one
# since they will permanently change the tensor

torch.Size([4, 4])

In [6]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([4, 4]) torch.Size([2, 2])


In [7]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


In [8]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)

tensor([7., 8., 9.])


Working with tensors is exactly the same than working with vectors and matrices!

In [9]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtract)
w_plus_v = w + v
# Element-wise multiplication (or division)
w_dot_v = w * v
# Square all elements in the tensor
w2 = w.pow(2)
# and so on...

print(w_plus_v, w_dot_v, w2)

tensor([10., 10., 10.]) tensor([21., 16.,  9.]) tensor([9., 4., 1.])


In [10]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [11]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:, 2])
# Get a row
print(m[1, :])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])


In [12]:
b = torch.randn(2,4)
# like with vectors you can
# Sum (or subtract)
m_plus_b = m + b
# Multiplication (or division)
m_dot_b = m * b

print(m_plus_b, m_dot_b)

tensor([[1.3891, 0.7321, 5.8313, 4.3739],
        [4.5125, 4.0372, 6.6631, 7.8969]]) tensor([[  0.3891,  -2.5358,   8.4938,   1.4958],
        [ -2.4376, -11.7770,  -2.3584,  -0.8250]])


In [13]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


Moving tensors to GPU

In [14]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(m_d.device)

cuda:0


Moving tensors to Numpy

In [15]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [16]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
