# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [1]:
#Let's start by importing the library
import torch

A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [3]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
t_2 = torch.Tensor(16,32,128,128)
t_3 = torch.Tensor(1, 3, 256, 256)
# .size() allows to get the size of the tensor
print(t.size(), t_2.size(), t_3.size())

torch.Size([2, 2, 4]) torch.Size([16, 32, 128, 128]) torch.Size([1, 3, 256, 256])


In [4]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)
t_zeros = torch.zeros(2,2,4)

In [5]:
# Print the tensors
print(t, t_r, t_ones, t_zeros)

tensor([[[-4.1648e-17,  1.6059e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]]) tensor([[[ 1.2139,  0.5739,  2.3323,  0.9436],
         [-1.4350,  0.8831, -0.9541, -0.7405]],

        [[-0.7077, -0.6542,  1.2276,  1.2713],
         [ 0.3673,  0.3336,  1.7920,  0.2050]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [7]:
# To resize a tensor do
#t_r.resize_(4,4)
#print(t_r.size(), t_r)
t_r.resize_(16,16)
print(t_r.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([16, 16])


In [8]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([2, 2, 4]) torch.Size([2, 2])


In [10]:
# An alternative is to use the .view() operator which do not alter the total number of dimensions of the tensor
t_v = torch.randn(4,4)
t_v1 = t_v.view(2,2,4)
print(t_v.size(), t_v1.size())
t_v2 = t_v.view(16,4)

torch.Size([4, 4]) torch.Size([2, 2, 4])


RuntimeError: shape '[16, 4]' is invalid for input of size 16

In [11]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)
t_ones.fill_(64)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])
tensor([[[64., 64., 64., 64.],
         [64., 64., 64., 64.]],

        [[64., 64., 64., 64.],
         [64., 64., 64., 64.]]])


In [15]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)
print(v.size())

tensor([7., 8., 9.])
torch.Size([3])


Working with tensors is exactly like working with vectors and matrices!

In [18]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
print(w2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])
tensor([9., 4., 1.])


In [19]:
# tensors need to have the same number of dimensions in order for them to be summed
q = torch.randn(2,4,2)
p = torch.randn(2,3,2)

print(q + p)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [22]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [23]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [24]:
# like with vectors you can do
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[1.7838, 3.1556, 4.6362, 4.5299],
        [4.5223, 6.5733, 6.6022, 7.1151]])
tensor([[ 0.7838,  2.3112,  4.9085,  2.1196],
        [-2.3886,  3.4401, -2.7846, -7.0789]])


In [25]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


In [26]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [30]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(device)
print(m_d.device)

m = m.cpu()
print(m.device)
m = m.cuda()
print(m.device)

cuda:0
cuda:0
cpu
cuda:0


Moving tensors to Numpy

In [33]:
# Converts tensor to numpy array
m_np = m.cpu().numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [34]:
a = torch.Tensor([[1, 2, 3, 4]]) # 1,4
b = torch.Tensor([[5, 6, 7, 8]]) # 1,4

# Concatenate on axis 0 -> 2,4
print(torch.cat((a, b), 0))
# Concatenate on axis 1 -> 1,8
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [38]:
c = torch.randn(3,4)
d = torch.randn(3,12)

print(torch.cat((c,d), 1)) # 3, 16

tensor([[ 0.4521,  0.9707,  1.2488,  0.1841, -1.9038,  1.0861, -0.4629,  1.1709,
          0.8174, -0.4928,  1.9464,  0.7625,  0.1279,  0.0952,  0.8903,  1.4029],
        [ 0.8303, -0.0769,  2.3003, -2.3154, -0.1178,  0.5294,  1.1793,  0.5984,
          1.3857, -0.4394, -1.0718, -0.1150,  0.0428,  0.5702, -0.4651, -0.4504],
        [-0.6364, -0.6351, -0.4043, -0.5707, -0.1205,  0.2930, -0.5272,  0.1435,
         -0.3641,  1.2122, -1.8301, -1.5816,  0.7431, -1.1127, -0.4414, -0.3965]])


In [42]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)

# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())

# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [ ]:
# Ex1: Split a 3 dimensional tensor of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them together to get the original size back

In [ ]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them together to form a single matrix
# of dimension 4x64x32

In [ ]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256