# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [1]:
#Let's start by importing the library
import torch

In [2]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
# .size() allows to get the size of the tensor
print(t.size())

torch.Size([2, 2, 4])


In [3]:
# Generate a random tensor  filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)

In [4]:
# Print both tensors
print(t, t_r, t_ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) tensor([[[ 1.0948,  0.3903,  0.4346,  0.2313],
         [ 0.4515,  0.5040, -0.2713,  1.8469]],

        [[-0.8041, -0.0508, -0.6740,  0.4557],
         [ 0.0405,  0.2780, -0.1603, -1.4202]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [5]:
# To resize a tensor do
t.resize_(4,4)
t.size()
# be CAREFULL with in-place operation like this one
# since they will permanently change the tensor

torch.Size([4, 4])

In [6]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([4, 4]) torch.Size([2, 2])


In [7]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


In [8]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)

tensor([7., 8., 9.])


Working with tensors is exactly the same than working with vectors and matrices!

In [9]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtract)
w_plus_v = w + v
# Element-wise multiplication (or division)
w_dot_v = w * v
# Square all elements in the tensor
w2 = w.pow(2)
# and so on...

print(w_plus_v, w_dot_v, w2)

tensor([10., 10., 10.]) tensor([21., 16.,  9.]) tensor([9., 4., 1.])


In [10]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [24]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:, 2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:,2:])
print(m[:,:2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [12]:
b = torch.randn(2,4)
# like with vectors you can
# Sum (or subtract)
m_plus_b = m + b
# Multiplication (or division)
m_dot_b = m * b

print(m_plus_b, m_dot_b)

tensor([[0.9084, 0.9827, 2.9911, 3.8484],
        [4.1470, 5.2106, 8.2275, 7.5105]]) tensor([[-0.0916, -2.0345, -0.0266, -0.6062],
        [-4.2652, -4.7366,  8.5923, -3.9161]])


In [13]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


Moving tensors to GPU

In [14]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(m_d.device)

cuda:0


Moving tensors to Numpy

In [15]:
# Converts tensor to numpy array
m_np = m.numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [16]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])

# Concatenate on axis 0
print(torch.cat((a, b), 0))
# Concatenate on axis 1
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [23]:
# Ex1: split a 3 dimentional matrix of dimention 4x64x128 
# into 2 matrixes of size 4x32x128
# and then concatenate them togher to get the original size back